[package]
name = "ksp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3.72"
serde = "1.0.215"
serde_json = "1.0.132"
serde-wasm-bindgen = "0.6"
wasm-bindgen = { version = "0.2" }

[dev-dependencies]
charming = "0.5"

[profile.release]
opt-level = "z"  # Optimize for size instead of speed
lto = true       # Enable Link-Time Optimization (LTO)
codegen-units = 1  # Reduce parallel codegen units for better optimization
panic = "abort"  # Remove panic handling to reduce binary size
strip = true     # Strip debug symbols (Rust 1.59+)

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Oz']

[package.metadata.wasm-pack.profile.release.wasm-bindgen]
debug-js-glue = false               # removes debug info from the generated js glue code
demangle-name-section = false       # controls whether function names are readable in stack traces
dwarf-debug-info = false            # removes DWARF debug info
omit-default-module-path = false    # removes default module path